#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# fox autostart

xrandr --output DP-1 --mode 1920x1080 --refresh 120
#ibus-daemon -d -r -x &
numlockx &
picom --backend glx --vsync --blur-method gaussian --blur-size 16 --blur-deviation 8 &
polybar &
~/.fehbg &
xinput set-prop 8 'libinput Accel Speed' -0.7 &
xsetroot -cursor_name left_ptr &
lxpolkit &

# fox bspwm settings

bspc config focused_border_color '#5294e2' 
bspc rule -a '*' state=floating
#bspc config focus_follows_pointer true
bspc config pointer_motion_interval 1
