#! /bin/sh

# Configuration file for BSPWM in second generation of Fox Desktop
# Based on Aditya Shakya's BSPWM config file in Archcraft

# General settings #

export XDG_CURRENT_DESKTOP='bspwm' # makes it easier than having to edit /etc/environment file every time
export _JAVA_AWT_WM_NONREPARENTING=1 # java specific configuration to run java apps smoothly

# Fox desktop settings # 

declare -a files=(pcmanfm) # defines file manager
declare -a code=(leafpad) # defines text editor
declare -a office=(Atril Evince libreoffice-writer libreoffice-calc libre-office-impress libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice) # allows libreoffice applications to be called accordingly
declare -a media=(Audacity Lxmusic Gimp obs) # set the media applications to function properly
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr pavucontrol) # define settings manager(s)

# Fox Bspwm Settings #

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 # specify monitor and workspace amount, set at 10 [single-monitor only]
bspc config border width 3 # sets how thick the borders should be
bspc config window_gap # sets how many pixels should be between windows when in tiling mode
bspc config split_ratio 0.50 # sets an even 50/50 split between two window containers in tiling mode
bspc config borderless_monocle true # allows a borderless full-screen single-window mode
bspc config gapless_monocle true # allows a gapless full-screen single-window mode 
bspc config paddingless_monocle true # allows paddingless full-screen single-window mode 
#bspc config focus_follows_pointer true # moving the mouse over a window will cause it to be focused
bspc rule -a '*' state=floating # sets all windows to floating mode, disable for tiling window manager mode 
bspc config pointer_motion_interval 1 # fixes lagginess when dragging windows around in floating mode

# Fox Autostart Section # 

killall -9 xsettingsd sxhkd dunst ksuperkey bspc # resets running services/applications from former sessions
xsettingsd --config=~/.config/xsettingsd & # launches xsettingsd daemon
pgrep -x sxhkd > /dev/null || sxhkd & # starts sxhkd keybind daemon # launches the keybinds daemon
xsetroot -cursor_name left_ptr & # changes from the default x cursor to the one chosen by the user
~/.fehbg & # restores the defined wallpaper
dunst & # starts the notification daemon
numlockx & # turns on numpad at startup
picom --backend glx --vsync --blur-method gaussian --blur-size 16 --blur-deviation 8 # enables compositing, vsync and blur
polybar & # launches polybar
xinput set-prop 8 'libinput Accel Speed' -0.8 & # lowers mouse speed so it is actually usable
xset -dpms s off & # disables powersaving so screen doesn't blank, and computer doesn't turn off

# Special Startup Section for Polkit Agent #

if [[ ! ` pidof lxpolkit` ]]; then
	/usr/lib/lxpolkit &
fi





