#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# fox general settings

xsetroot -cursor_name left_ptr &
xrandr --output DisplayPort-0 --mode 1920x1080 --refresh 120 &
xinput set-prop 11 'libinput Accel Speed' -0.75

# fox bspwm settings

bspc config pointer_motion_interval 7.5
bspc config focused_border_color '#ffffff'
bspc rule -a '*' state=floating

# fox autostart

fcitx5 &
numlockx &
picom --backend glx --vsync --corner-radius 12 &
lxpolkit &
pulseaudio &
~/.fehbg &
